spring.primary.datasource.driver-class-name: org.postgresql.Driver
spring.primary.datasource.url: jdbc:postgresql://localhost:5432/cb125_se?currentSchema=exelBatch
spring.primary.datasource.username: postgres
spring.primary.datasource.password: admin
spring.primary.hibernate.ddl-auto: none
spring.primary.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.primary.hibernate.show_sql: false